# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\projects\python\network\src\views\MainWindow.ui',
# licensing of 'D:\projects\python\network\src\views\MainWindow.ui' applies.
#
# Created: Sat Jul  4 13:09:46 2020
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(858, 586)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tab2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tab2.setObjectName("tab2")
        self.tabCameras = QtWidgets.QWidget()
        self.tabCameras.setObjectName("tabCameras")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabCameras)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tabCameras)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.list_cameras = QtWidgets.QListView(self.groupBox)
        self.list_cameras.setObjectName("list_cameras")
        self.verticalLayout.addWidget(self.list_cameras)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.add_camera = QtWidgets.QToolButton(self.tabCameras)
        self.add_camera.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.add_camera.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.add_camera.setAutoRaise(False)
        self.add_camera.setArrowType(QtCore.Qt.RightArrow)
        self.add_camera.setObjectName("add_camera")
        self.verticalLayout_2.addWidget(self.add_camera)
        self.delete_camera = QtWidgets.QToolButton(self.tabCameras)
        self.delete_camera.setArrowType(QtCore.Qt.LeftArrow)
        self.delete_camera.setObjectName("delete_camera")
        self.verticalLayout_2.addWidget(self.delete_camera)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabCameras)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.run_camera = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_camera.sizePolicy().hasHeightForWidth())
        self.run_camera.setSizePolicy(sizePolicy)
        self.run_camera.setObjectName("run_camera")
        self.gridLayout.addWidget(self.run_camera, 0, 2, 1, 1)
        self.config_camera = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_camera.sizePolicy().hasHeightForWidth())
        self.config_camera.setSizePolicy(sizePolicy)
        self.config_camera.setObjectName("config_camera")
        self.gridLayout.addWidget(self.config_camera, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.list_selected_cameras = QtWidgets.QListView(self.groupBox_2)
        self.list_selected_cameras.setObjectName("list_selected_cameras")
        self.verticalLayout_3.addWidget(self.list_selected_cameras)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.line = QtWidgets.QFrame(self.tabCameras)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.tab2.addTab(self.tabCameras, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.refresh_page2 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refresh_page2.sizePolicy().hasHeightForWidth())
        self.refresh_page2.setSizePolicy(sizePolicy)
        self.refresh_page2.setObjectName("refresh_page2")
        self.gridLayout_6.addWidget(self.refresh_page2, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.table_segmentation = QtWidgets.QTableWidget(self.tab_2)
        self.table_segmentation.setObjectName("table_segmentation")
        self.table_segmentation.setColumnCount(3)
        self.table_segmentation.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.table_segmentation.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_segmentation.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_segmentation.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_segmentation.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_segmentation.setHorizontalHeaderItem(2, item)
        self.gridLayout_8.addWidget(self.table_segmentation, 1, 0, 1, 1)
        self.tab2.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.start_calc_params = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_calc_params.sizePolicy().hasHeightForWidth())
        self.start_calc_params.setSizePolicy(sizePolicy)
        self.start_calc_params.setObjectName("start_calc_params")
        self.verticalLayout_5.addWidget(self.start_calc_params)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.plots = QtWidgets.QWidget()
        self.plots.setGeometry(QtCore.QRect(0, 0, 814, 316))
        self.plots.setObjectName("plots")
        self.scrollArea.setWidget(self.plots)
        self.gridLayout_2.addWidget(self.scrollArea, 1, 0, 2, 1)
        self.tab2.addTab(self.tab, "")
        self.gridLayout_7.addWidget(self.tab2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 858, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Всі камери", None, -1))
        self.add_camera.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.delete_camera.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Обрані камери", None, -1))
        self.run_camera.setText(QtWidgets.QApplication.translate("MainWindow", "Запустити", None, -1))
        self.config_camera.setText(QtWidgets.QApplication.translate("MainWindow", "Налаштування", None, -1))
        self.tab2.setTabText(self.tab2.indexOf(self.tabCameras), QtWidgets.QApplication.translate("MainWindow", "Камери", None, -1))
        self.refresh_page2.setText(QtWidgets.QApplication.translate("MainWindow", "Оновити", None, -1))
        self.table_segmentation.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Новая строка", None, -1))
        self.table_segmentation.verticalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Новая строка", None, -1))
        self.table_segmentation.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Новый столбец", None, -1))
        self.table_segmentation.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Новый столбец", None, -1))
        self.table_segmentation.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Новый столбец", None, -1))
        self.tab2.setTabText(self.tab2.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "Навчання мереж сегментації", None, -1))
        self.start_calc_params.setText(QtWidgets.QApplication.translate("MainWindow", "Почати визначення", None, -1))
        self.tab2.setTabText(self.tab2.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Визначення параметрів", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

